# Project: day1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = tast.o tast2.o se2-4.o
LINKOBJ  = tast.o tast2.o se2-4.o
LIBS     = -L"D:/porgarm/Dev-Cpp/MinGW64/lib" -L"D:/porgarm/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/porgarm/Dev-Cpp/MinGW64/include" -I"D:/porgarm/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/porgarm/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/porgarm/Dev-Cpp/MinGW64/include" -I"D:/porgarm/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/porgarm/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/porgarm/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = day1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

tast.o: tast.c
	$(CC) -c tast.c -o tast.o $(CFLAGS)

tast2.o: tast2.c
	$(CC) -c tast2.c -o tast2.o $(CFLAGS)

se2-4.o: se2-4.c
	$(CC) -c se2-4.c -o se2-4.o $(CFLAGS)
